name: CI - Mon Premier Pipeline  # Nom du workflow

on:  # Déclencheurs
  push:
    branches: [ main ]

jobs:  # Ensemble des jobs
  build:
    runs-on: ubuntu-latest  # Environnement du runner

    steps:  # Liste des étapes à exécuter
      - name: Etape 1
        run: echo "Hello CI"

      - name: Etape 2
        run: echo "Pipeline terminé"
